### ISSUE TITLE
Error when enabling URL Rewrite

### ISSUE THREAD

**Issue by OvalMedia** [igorppbr/magento2-warmcache#6]
When the URL Rewrite option is enabled the command line quits with this error message:

`PHP Fatal error:  Uncaught Error: Call to undefined method Magento\UrlRewrite\Model\UrlRewriteFactory::getCollection() in /web/vendor/igorludgero/warmcache/Helper/Data.php:145
Stack trace:
#0 /web/vendor/igorludgero/warmcache/Helper/Data.php(84): Igorludgero\WarmCache\Helper\Data->getUrls()
#1 /web/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111): Igorludgero\WarmCache\Helper\Data->__construct(Object(Magento\Framework\App\Helper\Context), Object(Magento\Catalog\Model\ProductFactory), Object(Magento\Catalog\Model\CategoryFactory), Object(Magento\Cms\Model\PageFactory), Object(Magento\UrlRewrite\Model\UrlRewriteFactory), Object(Magento\Framework\Url\Interceptor))
#2 /web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(108): Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Igorludgero\\War...', Array)
#3 /web/vendor/magento/framework/ObjectManager/Factory/Compiled.php(150): Magento\Framework\ObjectManager\Factory\Compiled->create('Igorludgero\\War...')
#4 /web/vendor/magent in /web/vendor/igorludgero/warmcache/Helper/Data.php on line 145`

Magento 2.2.9

**Comment by onepack** [comment]
Same here
